### ISSUE TITLE
basic npm test failing

### ISSUE THREAD

**Issue by Rajan** [crocodilejs/crocodile-node-mvc-framework#145]
glazed 2.0.0
node v6.3.0 (npm v3.10.3)
Darwin Rajans-MacBook-Pro.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64

ngoose: jobs.ensureIndex({ lockedAt: 1 }) { background: true }  
    1) should return 200 on GET /status

  0 passing (98ms)
  1 failing

  1) website should return 200 on GET /status:
     TypeError: Cannot read property 'indexOf' of null
      at Frisbee._callee$ (node_modules/frisbee/lib/frisbee.js:152:58)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:336:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:95:21)
      at step (node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
      at run (node_modules/core-js/modules/es6.promise.js:87:22)
      at node_modules/core-js/modules/es6.promise.js:100:28
      at flush (node_modules/core-js/modules/_microtask.js:18:9)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

npm ERR! Test failed.  See above for more details.

**Comment by niftylettuce** [comment]
@Rajan If you look at line 152 of `node_modules/frisbee/lib/frisbee.js` you'll see the following code block:

```js
                    if (!(res.headers.get('Content-Type').indexOf('application/json') !== -1)) {
                      _context.next = 18;
                      break;
                    }
```

For some reason the content-type header is missing on the response.

I can't seem to reproduce on my end yet.

**Comment by Rajan** [comment]
Are you on the same node/npm versions?
I will debug that today and update this thread.
Any pointers would be useful!

**Comment by Rajan** [comment]
I inspected HTTP headers for http://localhost:3000/status

They seem to be fine:

GET /status HTTP/1.1
Host: localhost:3000
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,ru;q=0.6
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
X-DevTools-Emulate-Network-Conditions-Client-Id: 2C64C4A0-395F-4874-BFB4-AF36956D3A82

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 24
**Content-Type: application/json; charset=utf-8**
Date: Fri, 22 Jul 2016 05:42:26 GMT
ETag: "18-BciYwdJEEajX5qe5v9F7ag"
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-DNS-Prefetch-Control: off
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Response-Time: 3ms
X-XSS-Protection: 1; mode=block

Seems like the problem is on the side of Test System. 
What do you think?

**Comment by niftylettuce** [comment]
@Rajan I will have to take a look this weekend, sorry

**Comment by Rajan** [comment]
It is passing now, I changed the port and hard coded params to Frisbee.

> let server = require('../../lib');
> 
> describe('website', () => {
> 
>   before(done => {
>     server = server.listen(3000, done);
>   });
> 
>   after(done => server.close(done));
> 
>   it('should return 200 on GET /status', async () => {
>     console.log(global._options);
>     const api = new global.Frisbee({ baseURI: 'http://localhost:3000' });
>     const res = await api.get('/status');
>     expect(res.body).to.be.an('object');
>     expect(res.body.status).to.equal('online');
>   });
> 
> });
