### ISSUE TITLE
Make it so the app runs without `.env` configuration

### ISSUE THREAD

**Issue by niftylettuce** [crocodilejs/crocodile-node-mvc-framework#149]

**Comment by gregbenner** [comment]
Seems to need an aws key to run?
`/crocodile-node-mvc-framework-master/node_modules/gulp-awspublish/lib/index.js:209
    throw new Error('Missing `params.Bucket` config value.');`

**Comment by niftylettuce** [comment]
Yeah sorry @gregbenner I renamed this project from Glazed to CrocodileJS - and am releasing v1.0.0 of it probably tonight - which rids the need for you to have an AWS key to run!
