### ISSUE TITLE
Add babel-register as a requirement in documentation

### ISSUE THREAD

**Issue by gregbenner** [crocodilejs/crocodile-node-mvc-framework#150]
* **Version**:
* **Platform**:
* **Subsystem**:

If babel-register is not installed locally or globally the project will not run. Should include that in the documentation, under installation step.

**Comment by niftylettuce** [comment]
@gregbenner Hey!  I actually took this out in the new version of CrocodileJS that is being released tonight.  You should join up in Slack if you already aren't so you can try it as soon as its released.  I usually do announcements to @channel in Slack so everyone gets pinged.  Thanks for patience!  <http://slack.crocodilejs.com>

**Comment by gregbenner** [comment]
@niftylettuce will do, looks like an exciting framework/boilerplate :smile:
