### ISSUE TITLE
Beta?

### ISSUE THREAD

**Issue by Rajan** [crocodilejs/crocodile-node-mvc-framework#156]
There hasn't been an update for a long and a number of dependencies are deprecated.
when are we launching the beta of the framework?

**Comment by niftylettuce** [comment]
Hi @Rajan I have been working when I can on this - join the Slack channel - as I am working on a multitude of things for the next release 👍 Soon!!!!!!

**Comment by niftylettuce** [comment]
@Rajan please join up slack, I have pushed to GitHub a draft of my WIP, will be releasing v1.0.0 as I tie up some loose ends
