### ISSUE TITLE
 NPM Run Watch Error

### ISSUE THREAD

**Issue by russellmiller3** [crocodilejs/crocodile-node-mvc-framework#215]
* **Version**: 2.0.0
* **Platform**:Darwin Russells-MacBook-Air.local 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64
Node: v6.0.0

* **Subsystem**:

NPM Run Watch causing errors. Screenshot attached.

![crocodile_error](https://cloud.githubusercontent.com/assets/6886512/18445560/0216872c-78d3-11e6-9171-2e9f8e305c05.png)

**Comment by niftylettuce** [comment]
@russellmiller3 hey, can you join me in Slack at http://slack.crocodilejs.com and I can explain this?
