### ISSUE TITLE
ls

### ISSUE THREAD

**Issue by tom-odon** [crocodilejs/crocodile-node-mvc-framework#241]
* **Version**:
* **Platform**:
* **Subsystem**:

**Comment by niftylettuce** [comment]
@tom-odon can you elaborate?  what is `ls`?

**Comment by tom-odon** [comment]
Hey, sorry there. You can close this issue. Typos on my end. Did this framework take over Eskimo?

**Comment by niftylettuce** [comment]
@tom-odon it was inspired by it, yes
