### ISSUE TITLE
An error occured while cloning the repository from GitHub

### ISSUE THREAD

**Issue by unclekitty** [crocodilejs/crocodile-node-mvc-framework#245]
* **Version**: 1.0.4
* **Platform**: v7.8.0
* **Subsystem**:Darwin kittydeMacBook-Pro.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64

🐊  CrocodileJS is a Node MVC framework that lets you chew apart JavaScript - https://crocodilejs.com

✗ An error occured while cloning the repository from GitHub, please try again or file an issue with the below output:

Error: Command failed: git describe --tags `git rev-list --tags --max-count=1`
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=<n>
    --max-age=<epoch>
    --min-age=<epoch>
    --sparse
    --no-merges
    --min-parents=<n>
    --no-min-parents
    --max-parents=<n>
    --no-max-parents
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=<n> | --no-abbrev
    --abbrev-commit
    --left-right
    --count
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all
fatal: No names found, cannot describe anything.
 `git describe --tags `git rev-list --tags --max-count=1`` (exited with error code 128)
    at callback (/usr/local/lib/node_modules/crocodile/node_modules/child-process-promise/lib/index.js:33:27)
    at ChildProcess.exithandler (child_process.js:212:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by niftylettuce** [comment]
Hi @unclekitty - please clone the repo (do not use the CLI) until we have publicly released a tagged version.  Thank you!

**Comment by niftylettuce** [comment]
Dup of #236
