### ISSUE TITLE
miss used on "git rev-list"

### ISSUE THREAD

**Issue by ronnin** [crocodilejs/crocodile-node-mvc-framework#250]
* **Version**: v7.10.0
* **Platform**: Darwin ronmac.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
* **Subsystem**:

✗ An error occured while cloning the repository from GitHub, please try again or file an issue with the below output:

Error: Command failed: git describe --tags `git rev-list --tags --max-count=1`
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=<n>
    --max-age=<epoch>
    --min-age=<epoch>
    --sparse
    --no-merges
    --min-parents=<n>
    --no-min-parents
    --max-parents=<n>
    --no-max-parents
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=<n> | --no-abbrev
    --abbrev-commit
    --left-right
    --count
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all
fatal: No names found, cannot describe anything.
 `git describe --tags `git rev-list --tags --max-count=1`` (exited with error code 128)
    at callback (/Users/ronnin/.config/yarn/global/node_modules/child-process-promise/lib/index.js:33:27)
    at ChildProcess.exithandler (child_process.js:212:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by niftylettuce** [comment]
dup of #236 - just fork/clone this repo instead of using `crocodile` cli
