### ISSUE TITLE
Breaks on install

### ISSUE THREAD

**Issue by WyzerrOps** [crocodilejs/crocodile-node-mvc-framework#251]
* **Version**:
* **Platform**:
* **Subsystem**:

Node version: 8.1.2
crocodile version 1.0.4
Macbook Pro x86-64 kernel version 15.6.0

I'm using nvm, brew, mongo 3.4, redis 3.0.4

I can't even get this to work at all.  This is the error I'm getting.

```
An error occured while cloning the repository from GitHub, please try again or file an issue with the below output:

Error: Command failed: git describe --tags `git rev-list --tags --max-count=1`
...
```

I saw that others were having issues as well in issue #220, but doesn't seem to be fixed.  What is crocodile-cli doing?  Should I just clone the project and rename the directory or is it doing more than that?

**Comment by niftylettuce** [comment]
Hey - You can just clone this repo directly if you'd like for now - I have to release v1.0 stable - should be out very soon.  I have a huge commit and even screencast + examples to share.  Join in Slack too! http://slack.crocodilejs.com

**Comment by WyzerrOps** [comment]
Cool.  I'll join the slack channel and watch for your release update.  Thanks.
