### ISSUE TITLE
Readme is missing links

### ISSUE THREAD

**Issue by OmgImAlexis** [crocodilejs/crocodile-node-mvc-framework#253]
In the proxy section the apache and nginx links are missing.

> You no longer need to install, configure, nor use [Apache's Virtual Hosts][apache-virtual-hosts] or [Nginx's Reverse Proxy][nginx-reverse-proxy]!

**Comment by niftylettuce** [comment]
already fixed locally, will be pushed with my next huge commit announcing the project
